"""create patients table

Revision ID: df17333ab6ba
Revises: 
Create Date: 2026-09-24 15:35:37.591713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df17333ab6ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.Enum('Male', 'Female', 'Other', 'Decline to Answer', name='patient_sex'), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('insurance_provider', sa.String(length=255), nullable=True),
    sa.Column('insurance_member_id', sa.String(length=64), nullable=True),
    sa.Column('preferred_language', sa.String(length=50), server_default=sa.text("'English'"), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("emergency_contact_phone IS NULL OR emergency_contact_phone ~ '^[0-9]{10}$'", name='ck_patients_emergency_contact_phone'),
    sa.CheckConstraint("first_name ~ '^[A-Za-z]+([''-][A-Za-z]+)*$' AND char_length(first_name) <= 50", name='ck_patients_first_name'),
    sa.CheckConstraint("insurance_member_id IS NULL OR insurance_member_id ~ '^[A-Za-z0-9]+$'", name='ck_patients_insurance_member_id'),
    sa.CheckConstraint("last_name ~ '^[A-Za-z]+([''-][A-Za-z]+)*$' AND char_length(last_name) <= 50", name='ck_patients_last_name'),
    sa.CheckConstraint("phone_number ~ '^[0-9]{10}$'", name='ck_patients_phone_number'),
    sa.CheckConstraint("state IN ('AK', 'AL', 'AR', 'AS', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'GU', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MP', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'PR', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VI', 'VT', 'WA', 'WI', 'WV', 'WY')", name='ck_patients_state'),
    sa.CheckConstraint("zip_code ~ '^[0-9]{5}(-[0-9]{4})?$'", name='ck_patients_zip_code'),
    sa.CheckConstraint('char_length(address_line_1) >= 1', name='ck_patients_address_line_1'),
    sa.CheckConstraint('char_length(city) BETWEEN 1 AND 100', name='ck_patients_city'),
    sa.CheckConstraint('date_of_birth <= CURRENT_DATE', name='ck_patients_date_of_birth'),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index('ix_patients_last_name_date_of_birth', 'patients', ['last_name', 'date_of_birth'], unique=False)
    op.create_index('ix_patients_phone_number', 'patients', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patients_phone_number', table_name='patients')
    op.drop_index('ix_patients_last_name_date_of_birth', table_name='patients')
    op.drop_table('patients')
    sa.Enum(name='patient_sex').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
